title: Portafolio de evidencias de Seguridad Informática.
decription: Compendio de actividades, análisis de vulnerabilidades y herramientas de Ciberseguridad.
theme: jekyll-theme-cayman # Tema visual limpio y moderno
show_downloads: false
